import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-gray-300 selection:bg-primary/30 pt-8 pb-24 px-6">
      <div className="max-w-3xl mx-auto space-y-12">
        <Link href="/">
          <Button variant="ghost" className="text-gray-500 hover:text-white -ml-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back
          </Button>
        </Link>

        <header className="space-y-4">
          <h1 className="text-4xl font-extrabold text-white tracking-tight">Terms of Service</h1>
          <p className="text-sm text-gray-500">Last updated: May 2026</p>
        </header>

        <main className="space-y-8 leading-relaxed">
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing and using JobSeed ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">2. Description of Service</h2>
            <p>
              JobSeed provides AI-driven code scaffolding and deployment automation tools.
              We reserve the right to modify or discontinue the Service at any time.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">3. User Responsibilities</h2>
            <p>
              You are responsible for maintaining the security of your account and for all activities that occur under your account.
              You must not use the Service for any illegal or unauthorized purpose.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">4. Intellectual Property</h2>
            <p>
              The code generated by the Service is yours to own. However, the Service's interface, logic, and underlying
              technology are protected by intellectual property laws.
            </p>
          </section>

          <section className="space-y-4 text-sm text-gray-500">
            <p>Questions? Contact us at support@jobseed.studio</p>
          </section>
        </main>
      </div>
    </div>
  );
}
